### ISSUE TITLE
Error after upgrade to 1.3.1

### ISSUE THREAD

**Issue by nflute** [mkormendy/homebridge-node-alarm-dot-com#22]
Keep receiving this in Homebridge log after upgrade to 1.3.1

[2019-11-19 12:13:11] [ADT] TypeError: Cannot read property 'forEach' of undefined
    at systemStates.forEach.system (/usr/local/lib/node_modules/homebridge-node-alarm-dot-com/index.js:227:24)
    at Array.forEach (<anonymous>)
    at login.then.then.systemStates (/usr/local/lib/node_modules/homebridge-node-alarm-dot-com/index.js:210:22)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)

Please help.

**Comment by mkormendy** [comment]
I forgot that my local version had the updates but I didn't publish the node alarm dot com dependency changes to NPM either. Please install the new version 1.3.2 - it will pull in the latest dependency.

**Comment by nflute** [comment]
Thank you for quick response.

**Comment by nflute** [comment]
All alarm accessories are now gone.

**Comment by mkormendy** [comment]
First try to uninstall the entire homebridge plugin. Remove it from your config as well. Then force refresh homebridge with the -R flag to clean up stale accessory data.

Then reinstall the plugin. Let me know how that goes.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by nflute** [comment]
> First try to uninstall the entire homebridge alarm.com plugin. Remove it from your config as well. Then force refresh homebridge with the -R flag to clean up stale accessory data.
> 
> Then reinstall the plugin. Let me know how that goes.
> 
> Sent with [GitHawk](http://githawk.com)

Try above still the same result. 

[2019-11-20 10:53:34] [ADT] Error: GET https://www.alarm.com/web/api/devices/lights/? failed: [object Object]
    at fetch.then.then.catch.err (/usr/local/lib/node_modules/homebridge-node-alarm-dot-com/node_modules/node-alarm-dot-com/index.js:482:13)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)
[2019-11-20 10:53:49] [Ikea Trådfri Gateway] Ping OK.
[2019-11-20 10:54:34] [ADT] Error: GET https://www.alarm.com/web/api/devices/locks/? failed: [object Object]
    at fetch.then.then.catch.err (/usr/local/lib/node_modules/homebridge-node-alarm-dot-com/node_modules/node-alarm-dot-com/index.js:482:13)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)
[2019-11-20 10:54:49] [Ikea Trådfri Gateway] Ping OK.
[2019-11-20 10:55:34] [ADT] Error: GET https://www.alarm.com/web/api/devices/lights/? failed: [object Object]
    at fetch.then.then.catch.err (/usr/local/lib/node_modules/homebridge-node-alarm-dot-com/node_modules/node-alarm-dot-com/index.js:482:13)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)

I do not have locks or lights connected to Alarm dot com - Not sure if it is related.

**Comment by nflute** [comment]
@mkormendy Any update on how to fix the issue.

**Comment by mkormendy** [comment]
I haven’t had time to look into it, I recommend pulling the previous version without the locks and lights and installing that instead for the time being.

**Comment by ngori** [comment]
When I was testing the lights and locks pull request  I had to clear the device cache to get it to work properly but if nflute did a full reinstall that should have wiped the device cache I would think


________________________________
