### ISSUE TITLE
Alarm.com not not appearing in Home app

### ISSUE THREAD

**Issue by kaganae** [mkormendy/homebridge-node-alarm-dot-com#25]
Added the plugin today, it is definitely connecting/authenticating to Alarm.com, because getting notifications that it is successfully logging in. Getting the below error message every minute in the log and no Alarm.com "accessories" are appearing in my Home app (other homebridge devices are).

[2019-11-23 23:04:42] [Security System] Logging into Alarm.com as ########
[2019-11-23 23:04:42] Homebridge is running on port 51826.
[2019-11-23 23:04:53] [Security System] Logged into Alarm.com as ########
[2019-11-23 23:04:59] [Security System] UNHANDLED ERROR: Error: GET https://www.alarm.com/web/api/devices/locks/? failed: [object Object]
    at fetch.then.then.catch.err (/usr/lib/node_modules/homebridge-node-alarm-dot-com/node_modules/node-alarm-dot-com/index.js:482:13)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)
[2019-11-23 23:05:42] [Security System] Error: GET https://www.alarm.com/web/api/devices/locks/? failed: [object Object]
    at fetch.then.then.catch.err (/usr/lib/node_modules/homebridge-node-alarm-dot-com/node_modules/node-alarm-dot-com/index.js:482:13)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)

config.json:

{
	"bridge": {
		"name": "Kagan RaspberryPi",
		"username": "AA:11:33:EE:EE:30",
		"port": 51826,
		"pin": "765-99-210"
	},
	"description": "Homekit Server",
	"accessories": [],
	"platforms": [
		{
			"platform": "Alarmdotcom",
			"name": "Security System",
			"username": "######",
			"password": "######",
			"armingModes": {
				"away": {
					"noEntryDelay": false,
					"silentArming": false
				},
				"night": {
					"noEntryDelay": false,
					"silentArming": false
				},
				"stay": {
					"noEntryDelay": false,
					"silentArming": false
				}
			}
		}
	]
}

**Comment by lwpmoon** [comment]
Duplicate issue #23
