### ISSUE TITLE
Error with HomeBridge

### ISSUE THREAD

**Issue by dvalenzuela** [mkormendy/homebridge-node-alarm-dot-com#31]
Created the following config.json inside ./homebridge (username and password are fake)
`{
    "platform": "Alarmdotcom",
    "name": "Security System",
    "username": "email@email.com",
    "password": "password",
    "armingModes": {
        "away": {
            "noEntryDelay": false,
            "silentArming": false
        },
        "night": {
            "noEntryDelay": false,
            "silentArming": false
        },
        "stay": {
            "noEntryDelay": false,
            "silentArming": false
        }
    }
}
`

The result of executing homebridge is the following
dMini:.homebridge diegovalenzuela$ homebridge
/usr/local/lib/node_modules/homebridge/lib/server.js:230
  var username = config.bridge.username;
                               ^

TypeError: Cannot read property 'username' of undefined
    at Server._loadConfig (/usr/local/lib/node_modules/homebridge/lib/server.js:230:32)
    at new Server (/usr/local/lib/node_modules/homebridge/lib/server.js:56:38)
    at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:32:16)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (internal/modules/cjs/loader.js:722:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:733:10)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:560:12)
    at Function.Module._load (internal/modules/cjs/loader.js:552:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:775:12)
dMini:.homebridge diegovalenzuela$

**Comment by mkormendy** [comment]
Seems like your config file is incorrect. Can you copy and paste the entire thing here, and redact the sensitive information?

**Comment by dvalenzuela** [comment]
Please find attached
{
	"platform": "Alarmdotcom",
	"name": "Security System",
	"username": " ",
	"password": " ",
	"armingModes": {
		"away": {
			"noEntryDelay": false,
			"silentArming": false
		},
		"night": {
			"noEntryDelay": false,
			"silentArming": false
		},
		"stay": {
			"noEntryDelay": false,
			"silentArming": false
		}
	}
}

**Comment by mkormendy** [comment]
Okay it appears like you are missing a larger portion of the homebridge config file and that you need to grasp the basics of how homebridge works before installing my plugin.

Unfortunately I don't provide support on homebridge itself. But I would do some research on how to get started with homebridge first before coming here.
