### ISSUE TITLE
Error loading plugin

### ISSUE THREAD

**Issue by knaackville** [mkormendy/homebridge-node-alarm-dot-com#5]
Hi there,

Trying to move from Bryan Bartow's plugin version to yours, but getting the error noted below.  Any thoughts?  Thanks!

[9/9/2018, 9:42:24 PM] ====================
[9/9/2018, 9:42:24 PM] ERROR LOADING PLUGIN homebridge-node-alarm-dot-com:
[9/9/2018, 9:42:24 PM] Error: Cannot find module '/package'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (C:\Users\Server\AppData\Roaming\npm\node_modules\homebridge-node-alarm-dot-com\node_modules\node-alarm-dot-com\index.js:20:5)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
[9/9/2018, 9:42:24 PM] ====================
[9/9/2018, 9:42:24 PM] Loading 4 platforms...
C:\Users\Server\AppData\Roaming\npm\node_modules\homebridge\lib\api.js:122
      throw new Error("The requested platform '" + name + "' was not registered by any plugin.");
      ^

Error: The requested platform 'Alarmdotcom' was not registered by any plugin.
    at API.platform (C:\Users\Server\AppData\Roaming\npm\node_modules\homebridge\lib\api.js:122:13)
    at Server._loadPlatforms (C:\Users\Server\AppData\Roaming\npm\node_modules\homebridge\lib\server.js:316:45)
    at Server.run (C:\Users\Server\AppData\Roaming\npm\node_modules\homebridge\lib\server.js:86:36)
    at module.exports (C:\Users\Server\AppData\Roaming\npm\node_modules\homebridge\lib\cli.js:45:10)
    at Object.<anonymous> (C:\Users\Server\AppData\Roaming\npm\node_modules\homebridge\bin\homebridge:17:22)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)

**Comment by mkormendy** [comment]
Hrmm .. What are you using for the configuration?

**Comment by knaackville** [comment]
Pretty much the config in the readme.  Deleting the "Alarmdotcom" section in the config itself removes the second half of the errors (the second "====================" onward, while keeping the first half of the errors) and allows my other homebridge plugins to start.  

I updated nodejs, npm, homebridge, the rest of the plugins, etc. with no change, though everything else seems to run just fine.

**Comment by mkormendy** [comment]
Locate the following file on your computer and open it in a text editor:

`C:\Users\Server\AppData\Roaming\npm\node_modules\homebridge-node-alarm-dot-com\node_modules\node-alarm-dot-com\index.js`

... try to replace the following lines:

```
// if the name of the parent package calling this script is frontpoint
if (require(module.parent.filename.split("/").slice(0,-1).join("/")+'/package').name === 'frontpoint') {
  isFP = true
  UA = `node-frontpoint/${require('./package').version}`
}
else {
  UA = `node-alarm-dot-com/${require('./package').version}`
}
```

with:

```
UA = `node-alarm-dot-com/${require('./package').version}`
```

Restart homebridge and let me know if that fixes it.

**Comment by knaackville** [comment]
That seems to have worked!  Thanks!

**Comment by mkormendy** [comment]
I’ll have this fixed in the next release. My bad implementation on attempting to detect the parent package isn’t working well on windows systems. Didn’t expect anyone to run Apple HomeKit with homebridge on Windows.

**Comment by jnanes** [comment]
IKR !

Hard to design for all these scenarios but man you did an awesome job! Congrats on the great work.
